package be.ehb.tristan.javaadvanced.internquest.enums;

public enum Industry {
    AEROSPACE_AND_DEFENSE,
    AGRICULTURE,
    CONSTRUCTION,
    EDUCATION,
    ENTERTAINMENT,
    FINANCE,
    GOVERNMENT,
    HEALTHCARE,
    INDUSTRIAL,
    INFORMATION_TECHNOLOGY,
    LOGISTICS_AND_SUPPLY_CHAIN,
    MANUFACTURING,
    MEDIA_AND_COMMUNICATIONS,
    PHARMACEUTICALS,
    REAL_ESTATE,
    RETAIL,
    TRANSPORT,
    WHOLESALE,
    INSURANCE,
    NON_PROFIT_AND_SOCIAL_SERVICES,
}
